"""Add custom_equipment to users

Revision ID: cccc93e89869
Revises: c32517467a35
Create Date: 2026-08-12 09:08:19.245389

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cccc93e89869'
down_revision: Union[str, Sequence[str], None] = 'c32517467a35'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('custom_equipment', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'custom_equipment')
    # ### end Alembic commands ###
