"""Add session_duration_code and specific_days to users

Revision ID: 0389fc0104a7
Revises: cccc93e89869
Create Date: 2026-08-15 20:40:42.077980

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0389fc0104a7'
down_revision: Union[str, Sequence[str], None] = 'cccc93e89869'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('session_duration_code', sa.String(), nullable=True))
    op.add_column('users', sa.Column('specific_days', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'specific_days')
    op.drop_column('users', 'session_duration_code')
    # ### end Alembic commands ###
