"""add_warning_message_to_conditions

Revision ID: add346a713ab
Revises: ed27fdc2f7de
Create Date: 2026-08-16 10:03:10.090280

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'add346a713ab'
down_revision: Union[str, Sequence[str], None] = 'ed27fdc2f7de'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conditions', sa.Column('warning_message', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('conditions', 'warning_message')
    # ### end Alembic commands ###
