"""Add new equipment models

Revision ID: c32517467a35
Revises: bca73ed19b76
Create Date: 2026-08-11 17:20:28.285418

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c32517467a35'
down_revision: Union[str, Sequence[str], None] = 'bca73ed19b76'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('everyday_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('mapping', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_everyday_item_code'), 'everyday_item', ['code'], unique=True)
    op.create_index(op.f('ix_everyday_item_id'), 'everyday_item', ['id'], unique=False)
    op.create_index(op.f('ix_everyday_item_name'), 'everyday_item', ['name'], unique=True)
    op.create_table('gym_equipment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('mapping', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_gym_equipment_code'), 'gym_equipment', ['code'], unique=True)
    op.create_index(op.f('ix_gym_equipment_id'), 'gym_equipment', ['id'], unique=False)
    op.create_table('home_equipment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('mapping', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_home_equipment_code'), 'home_equipment', ['code'], unique=True)
    op.create_index(op.f('ix_home_equipment_id'), 'home_equipment', ['id'], unique=False)
    op.create_table('outdoor_equipment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('mapping', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_outdoor_equipment_code'), 'outdoor_equipment', ['code'], unique=True)
    op.create_index(op.f('ix_outdoor_equipment_id'), 'outdoor_equipment', ['id'], unique=False)
    op.create_table('workout_hybrid_places',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workout_hybrid_places_code'), 'workout_hybrid_places', ['code'], unique=True)
    op.create_index(op.f('ix_workout_hybrid_places_id'), 'workout_hybrid_places', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_workout_hybrid_places_id'), table_name='workout_hybrid_places')
    op.drop_index(op.f('ix_workout_hybrid_places_code'), table_name='workout_hybrid_places')
    op.drop_table('workout_hybrid_places')
    op.drop_index(op.f('ix_outdoor_equipment_id'), table_name='outdoor_equipment')
    op.drop_index(op.f('ix_outdoor_equipment_code'), table_name='outdoor_equipment')
    op.drop_table('outdoor_equipment')
    op.drop_index(op.f('ix_home_equipment_id'), table_name='home_equipment')
    op.drop_index(op.f('ix_home_equipment_code'), table_name='home_equipment')
    op.drop_table('home_equipment')
    op.drop_index(op.f('ix_gym_equipment_id'), table_name='gym_equipment')
    op.drop_index(op.f('ix_gym_equipment_code'), table_name='gym_equipment')
    op.drop_table('gym_equipment')
    op.drop_index(op.f('ix_everyday_item_name'), table_name='everyday_item')
    op.drop_index(op.f('ix_everyday_item_id'), table_name='everyday_item')
    op.drop_index(op.f('ix_everyday_item_code'), table_name='everyday_item')
    op.drop_table('everyday_item')
    # ### end Alembic commands ###
