"""initial_schema

Revision ID: a69f5758c1f7
Revises: 
Create Date: 2026-07-06 18:41:34.196622

"""
import os
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a69f5758c1f7'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

# Helper para cargar los archivos SQL de optimización modularizados
MIGRATION_DIR = os.path.dirname(__file__)
SQL_DIR = os.path.abspath(os.path.join(MIGRATION_DIR, "..", "sql"))

def read_sql_file(filename: str) -> str:
    path = os.path.join(SQL_DIR, filename)
    with open(path, "r", encoding="utf-8") as f:
        return f.read()


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('active_break_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=False),
    sa.Column('instructions', sa.Text(), nullable=True),
    sa.Column('video_url', sa.String(), nullable=True),
    sa.Column('image_url', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_active_break_sessions_id'), 'active_break_sessions', ['id'], unique=False)
    op.create_table('conditions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_conditions_code'), 'conditions', ['code'], unique=True)
    op.create_index(op.f('ix_conditions_id'), 'conditions', ['id'], unique=False)
    op.create_table('enterprises',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('logo_url', sa.String(), nullable=True),
    sa.Column('contact_email', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_enterprises_id'), 'enterprises', ['id'], unique=False)
    op.create_table('equipment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_equipment_id'), 'equipment', ['id'], unique=False)
    op.create_index(op.f('ix_equipment_name'), 'equipment', ['name'], unique=True)
    op.create_table('excersices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('muscle_group', sa.String(length=100), nullable=False),
    sa.Column('pattern', sa.Enum('DOMINANTE_RODILLA', 'DOMINANTE_CADERA', 'DOMINANTE_CADERA_UNILATERAL', 'UNILATERAL', 'FLEXION_RODILLA', 'EXTENSION_RODILLA', 'FLEXION_PLANTAR', 'EXTENSION_CADERA', 'ABDUCCION', 'ADUCCION', 'ISOMETRICO', 'PLIOMETRIA', 'PLIOMETRICO', 'EMPUJE_HORIZONTAL', 'EMPUJE_INCLINADO', 'EMPUJE_DECLINADO', 'EMPUJE_UNILATERAL', 'EMPUJE_VERTICAL', 'EMPUJE_VERTICAL_EXPLOSIVO', 'EMPUJE_DIAGONAL', 'EMPUJE_DINAMICO', 'TRACCION_HORIZONTAL', 'TRACCION_HORIZONTAL_UNILATERAL', 'TRACCION_VERTICAL', 'TRACCION_PARCIAL', 'ADUCCION_HORIZONTAL', 'ABDUCCION_HORIZONTAL', 'ABDUCCION_HOMBRO', 'EXTENSION_HOMBRO', 'FLEXION_HOMBRO', 'ELEVACION_ESCAPULAR', 'RETRACCION_ESCAPULAR', 'CONTROL_ESCAPULAR', 'ESTABILIDAD_ESCAPULAR', 'EXTENSION_ESPINAL', 'TRANSPORTE_DE_CARGA', 'LOCOMOCION', 'LOCOMOCION_NO_ACCENT', 'ANTI_ROTACION', 'ANTIROTACIONAL', 'ANTIROTACIONAL_METABOLICO', 'ROTACIONAL', 'FLEXION_DE_CODO', 'FLEXION_DE_CODO_NEUTRA', 'FLEXION_DE_CODO_UNILATERAL', 'EXTENSION_DE_CODO', 'ROTACION_EXTERNA_EMPUJE', 'CORE_ANTERIOR', 'CORE_POSTERIOR', 'CORE_LATERAL', 'CORE_AVANZADO', 'MOVILIDAD_CORE', 'ESTABILIZACION', 'AEROBICO', 'ANAEROBICO', 'MIXTO', 'AGILIDAD', 'CORE_METABOLICO', name='excersice_pattern'), nullable=False),
    sa.Column('location', sa.String(length=100), nullable=False),
    sa.Column('complexity', sa.String(length=50), nullable=False),
    sa.Column('level', sa.String(length=100), nullable=False),
    sa.Column('fatigue', sa.String(length=50), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_excersices_code'), 'excersices', ['code'], unique=True)
    op.create_index(op.f('ix_excersices_id'), 'excersices', ['id'], unique=False)
    op.create_table('goals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=10), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_goals_code'), 'goals', ['code'], unique=True)
    op.create_index(op.f('ix_goals_id'), 'goals', ['id'], unique=False)
    op.create_table('levels',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=10), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_levels_code'), 'levels', ['code'], unique=True)
    op.create_index(op.f('ix_levels_id'), 'levels', ['id'], unique=False)
    op.create_table('methods',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('type', sa.String(length=100), nullable=False),
    sa.Column('level', sa.String(length=100), nullable=False),
    sa.Column('complexity', sa.String(length=50), nullable=False),
    sa.Column('intensity', sa.String(length=50), nullable=True),
    sa.Column('tempo', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_methods_code'), 'methods', ['code'], unique=True)
    op.create_index(op.f('ix_methods_id'), 'methods', ['id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('auth_provider', sa.String(), nullable=True),
    sa.Column('first_name', sa.String(), nullable=False),
    sa.Column('last_name', sa.String(), nullable=False),
    sa.Column('phone', sa.String(), nullable=False),
    sa.Column('age', sa.Integer(), nullable=False),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.Column('height', sa.Float(), nullable=False),
    sa.Column('exercise_frequency', sa.String(), nullable=False),
    sa.Column('training_type', sa.String(), nullable=False),
    sa.Column('gender', sa.String(), nullable=True),
    sa.Column('profile_picture_url', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('active_break_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('enterprise_id', sa.Integer(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed', sa.Boolean(), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['enterprise_id'], ['enterprises.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['active_break_sessions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_active_break_logs_id'), 'active_break_logs', ['id'], unique=False)
    op.create_table('coach_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('specialty', sa.String(length=50), nullable=False),
    sa.Column('experience_years', sa.Integer(), nullable=False),
    sa.Column('certifications', sa.Text(), nullable=True),
    sa.Column('hourly_rate', sa.Float(), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('state', sa.String(length=100), nullable=True),
    sa.Column('service_radius_km', sa.Float(), nullable=False),
    sa.Column('is_available', sa.Boolean(), nullable=False),
    sa.Column('available_hours', sa.Text(), nullable=True),
    sa.Column('avg_rating', sa.Float(), nullable=False),
    sa.Column('total_reviews', sa.Integer(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_searchable', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_coach_profiles_id'), 'coach_profiles', ['id'], unique=False)
    op.create_table('competitions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('creator_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('sport_type', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('start_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('location_name', sa.String(length=300), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('max_participants', sa.Integer(), nullable=True),
    sa.Column('rules', sa.Text(), nullable=True),
    sa.Column('prize_description', sa.Text(), nullable=True),
    sa.Column('cover_image_url', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['creator_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_competitions_id'), 'competitions', ['id'], unique=False)
    op.create_table('enterprise_codes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('enterprise_id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('is_used', sa.Boolean(), nullable=False),
    sa.Column('used_by_user_id', sa.Integer(), nullable=True),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['enterprise_id'], ['enterprises.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['used_by_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_enterprise_codes_code'), 'enterprise_codes', ['code'], unique=True)
    op.create_index(op.f('ix_enterprise_codes_id'), 'enterprise_codes', ['id'], unique=False)
    op.create_table('enterprise_members',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('enterprise_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('joined_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['enterprise_id'], ['enterprises.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_enterprise_members_id'), 'enterprise_members', ['id'], unique=False)
    op.create_table('events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('creator_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('location_name', sa.String(length=300), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('start_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('max_participants', sa.Integer(), nullable=True),
    sa.Column('is_public', sa.Boolean(), nullable=False),
    sa.Column('cover_image_url', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['creator_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_events_id'), 'events', ['id'], unique=False)
    op.create_table('excersice_condition',
    sa.Column('excersice_id', sa.Integer(), nullable=False),
    sa.Column('condition_id', sa.Integer(), nullable=False),
    sa.Column('relationship', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['condition_id'], ['conditions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['excersice_id'], ['excersices.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('excersice_id', 'condition_id')
    )
    op.create_table('excersice_equipment',
    sa.Column('excersice_id', sa.Integer(), nullable=False),
    sa.Column('equipment_id', sa.Integer(), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['equipment_id'], ['equipment.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['excersice_id'], ['excersices.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('excersice_id', 'equipment_id')
    )
    op.create_table('excersice_goal',
    sa.Column('excersice_id', sa.Integer(), nullable=False),
    sa.Column('goal_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['excersice_id'], ['excersices.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['goal_id'], ['goals.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('excersice_id', 'goal_id')
    )
    op.create_table('method_goal',
    sa.Column('method_id', sa.Integer(), nullable=False),
    sa.Column('goal_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['goal_id'], ['goals.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['method_id'], ['methods.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('method_id', 'goal_id')
    )
    op.create_table('programming_matrix',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('goal_code', sa.String(length=50), nullable=False),
    sa.Column('level_code', sa.String(length=50), nullable=False),
    sa.Column('volume', sa.String(length=50), nullable=False),
    sa.Column('sets', sa.Integer(), nullable=False),
    sa.Column('reps', sa.String(length=50), nullable=False),
    sa.Column('rest', sa.String(length=50), nullable=False),
    sa.Column('method_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['method_id'], ['methods.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_programming_matrix_id'), 'programming_matrix', ['id'], unique=False)
    op.create_table('prompt_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('system_prompt', sa.Text(), nullable=False),
    sa.Column('user_prompt', sa.Text(), nullable=False),
    sa.Column('ai_response', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_prompt_logs_id'), 'prompt_logs', ['id'], unique=False)
    op.create_index(op.f('ix_prompt_logs_user_id'), 'prompt_logs', ['user_id'], unique=False)
    op.create_table('user_disease',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('disease_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['disease_id'], ['conditions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'disease_id')
    )
    op.create_table('user_equipment',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('equipment_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['equipment_id'], ['equipment.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'equipment_id')
    )
    op.create_table('user_pathology',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('pathology_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['pathology_id'], ['conditions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'pathology_id')
    )
    op.create_table('user_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('goal_id', sa.Integer(), nullable=True),
    sa.Column('level_id', sa.Integer(), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('weight', sa.Float(), nullable=True),
    sa.Column('height', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['goal_id'], ['goals.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['level_id'], ['levels.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('coach_athletes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('coach_id', sa.Integer(), nullable=False),
    sa.Column('athlete_id', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['athlete_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['coach_id'], ['coach_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_coach_athletes_id'), 'coach_athletes', ['id'], unique=False)
    op.create_table('coach_bookings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('coach_id', sa.Integer(), nullable=False),
    sa.Column('athlete_id', sa.Integer(), nullable=False),
    sa.Column('scheduled_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=False),
    sa.Column('session_type', sa.String(length=50), nullable=True),
    sa.Column('location_name', sa.String(length=300), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('total_price', sa.Float(), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('athlete_notes', sa.Text(), nullable=True),
    sa.Column('coach_notes', sa.Text(), nullable=True),
    sa.Column('athlete_rating', sa.Float(), nullable=True),
    sa.Column('athlete_review', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['athlete_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['coach_id'], ['coach_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_coach_bookings_id'), 'coach_bookings', ['id'], unique=False)
    op.create_table('competition_participants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('competition_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('position', sa.Integer(), nullable=True),
    sa.Column('joined_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['competition_id'], ['competitions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('competition_id', 'user_id', name='uq_competition_participant')
    )
    op.create_index(op.f('ix_competition_participants_id'), 'competition_participants', ['id'], unique=False)
    op.create_table('event_participants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('joined_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_id', 'user_id', name='uq_event_participant')
    )
    op.create_index(op.f('ix_event_participants_id'), 'event_participants', ['id'], unique=False)
    op.create_table('training_plans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('coach_id', sa.Integer(), nullable=False),
    sa.Column('athlete_id', sa.Integer(), nullable=False),
    sa.Column('month', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'PROPOSED', 'ACCEPTED', 'REJECTED', 'COMPLETED', name='planstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['athlete_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['coach_id'], ['coach_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_training_plans_id'), 'training_plans', ['id'], unique=False)
    op.create_table('daily_workouts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('plan_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'COMPLETED', 'SKIPPED', name='workoutstatus'), nullable=False),
    sa.Column('coach_validated', sa.Boolean(), nullable=False),
    sa.Column('validation_date', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['plan_id'], ['training_plans.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_daily_workouts_id'), 'daily_workouts', ['id'], unique=False)
    op.create_table('exercise_details',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('workout_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('sets', sa.Integer(), nullable=True),
    sa.Column('reps', sa.Integer(), nullable=True),
    sa.Column('weight', sa.Float(), nullable=True),
    sa.Column('order', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['workout_id'], ['daily_workouts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_exercise_details_id'), 'exercise_details', ['id'], unique=False)
    
    # ─── OPTIMIZACIONES PERSONALIZADAS DE BASE DE DATOS ──────────────────────────
    # Cargar y ejecutar las optimizaciones modularizadas desde los archivos SQL
    op.execute(read_sql_file("create_vw_excersice_details.sql"))
    op.execute(read_sql_file("create_fn_get_viable_exercises.sql"))
    op.execute(read_sql_file("create_triggers.sql"))
    op.execute(read_sql_file("create_indexes.sql"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_exercise_details_id'), table_name='exercise_details')
    op.drop_table('exercise_details')
    op.drop_index(op.f('ix_daily_workouts_id'), table_name='daily_workouts')
    op.drop_table('daily_workouts')
    op.drop_index(op.f('ix_training_plans_id'), table_name='training_plans')
    op.drop_table('training_plans')
    op.drop_index(op.f('ix_event_participants_id'), table_name='event_participants')
    op.drop_table('event_participants')
    op.drop_index(op.f('ix_competition_participants_id'), table_name='competition_participants')
    op.drop_table('competition_participants')
    op.drop_index(op.f('ix_coach_bookings_id'), table_name='coach_bookings')
    op.drop_table('coach_bookings')
    op.drop_index(op.f('ix_coach_athletes_id'), table_name='coach_athletes')
    op.drop_table('coach_athletes')
    op.drop_table('user_profiles')
    op.drop_table('user_pathology')
    op.drop_table('user_equipment')
    op.drop_table('user_disease')
    op.drop_index(op.f('ix_prompt_logs_user_id'), table_name='prompt_logs')
    op.drop_index(op.f('ix_prompt_logs_id'), table_name='prompt_logs')
    op.drop_table('prompt_logs')
    op.drop_index(op.f('ix_programming_matrix_id'), table_name='programming_matrix')
    op.drop_table('programming_matrix')
    op.drop_table('method_goal')
    op.drop_table('excersice_goal')
    op.drop_table('excersice_equipment')
    op.drop_table('excersice_condition')
    op.drop_index(op.f('ix_events_id'), table_name='events')
    op.drop_table('events')
    op.drop_index(op.f('ix_enterprise_members_id'), table_name='enterprise_members')
    op.drop_table('enterprise_members')
    op.drop_index(op.f('ix_enterprise_codes_id'), table_name='enterprise_codes')
    op.drop_index(op.f('ix_enterprise_codes_code'), table_name='enterprise_codes')
    op.drop_table('enterprise_codes')
    op.drop_index(op.f('ix_competitions_id'), table_name='competitions')
    op.drop_table('competitions')
    op.drop_index(op.f('ix_coach_profiles_id'), table_name='coach_profiles')
    op.drop_table('coach_profiles')
    op.drop_index(op.f('ix_active_break_logs_id'), table_name='active_break_logs')
    op.drop_table('active_break_logs')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_methods_id'), table_name='methods')
    op.drop_index(op.f('ix_methods_code'), table_name='methods')
    op.drop_table('methods')
    op.drop_index(op.f('ix_levels_id'), table_name='levels')
    op.drop_index(op.f('ix_levels_code'), table_name='levels')
    op.drop_table('levels')
    op.drop_index(op.f('ix_goals_id'), table_name='goals')
    op.drop_index(op.f('ix_goals_code'), table_name='goals')
    op.drop_table('goals')
    op.drop_index(op.f('ix_excersices_id'), table_name='excersices')
    op.drop_index(op.f('ix_excersices_code'), table_name='excersices')
    op.drop_table('excersices')
    op.drop_index(op.f('ix_equipment_name'), table_name='equipment')
    op.drop_index(op.f('ix_equipment_id'), table_name='equipment')
    op.drop_table('equipment')
    op.drop_index(op.f('ix_enterprises_id'), table_name='enterprises')
    op.drop_table('enterprises')
    op.drop_index(op.f('ix_conditions_id'), table_name='conditions')
    op.drop_index(op.f('ix_conditions_code'), table_name='conditions')
    op.drop_table('conditions')
    op.drop_index(op.f('ix_active_break_sessions_id'), table_name='active_break_sessions')
    op.drop_table('active_break_sessions')
    
    # ─── LIMPIEZA DE OPTIMIZACIONES PERSONALIZADAS ────────────────────────────────
    # Deshacer índices adicionales
    op.execute("DROP INDEX IF EXISTS idx_programming_matrix_goal_level;")
    op.execute("DROP INDEX IF EXISTS idx_excersice_equipment_ex_eq;")
    op.execute("DROP INDEX IF EXISTS idx_excersice_condition_ex_cond;")
    op.execute("DROP INDEX IF EXISTS idx_excersice_goal_ex_goal;")
    op.execute("DROP INDEX IF EXISTS idx_user_equipment_user_eq;")
    op.execute("DROP INDEX IF EXISTS idx_user_disease_user_cond;")
    op.execute("DROP INDEX IF EXISTS idx_user_pathology_user_cond;")
    op.execute("DROP INDEX IF EXISTS idx_user_profiles_goal_level;")
    op.execute("DROP INDEX IF EXISTS idx_excersices_name_trgm;")
    
    # Deshacer triggers
    op.execute("DROP TRIGGER IF EXISTS trg_rotate_training_plans ON training_plans;")
    op.execute("DROP FUNCTION IF EXISTS fn_rotate_user_training_plans();")
    op.execute("DROP TRIGGER IF EXISTS trg_update_user_profiles_timestamp ON user_profiles;")
    op.execute("DROP TRIGGER IF EXISTS trg_update_users_timestamp ON users;")
    op.execute("DROP FUNCTION IF EXISTS fn_update_timestamp();")
    
    # Deshacer función y vista
    op.execute("DROP FUNCTION IF EXISTS fn_get_viable_exercises(INT);")
    op.execute("DROP VIEW IF EXISTS vw_excersice_details;")
    # ### end Alembic commands ###
