"""create_health_questions_table

Revision ID: ed27fdc2f7de
Revises: 14ec06419b87
Create Date: 2026-08-16 09:56:54.634967

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ed27fdc2f7de'
down_revision: Union[str, Sequence[str], None] = '14ec06419b87'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('health_questions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=250), nullable=False),
    sa.Column('subtitle', sa.String(length=250), nullable=True),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_health_questions_code'), 'health_questions', ['code'], unique=True)
    op.create_index(op.f('ix_health_questions_id'), 'health_questions', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_health_questions_id'), table_name='health_questions')
    op.drop_index(op.f('ix_health_questions_code'), table_name='health_questions')
    op.drop_table('health_questions')
    # ### end Alembic commands ###
