"""add_prompt_logs_table

Revision ID: 7ce7523512ad
Revises: 0001_initial
Create Date: 2026-05-08 13:53:00.077007

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7ce7523512ad'
down_revision: Union[str, Sequence[str], None] = '0001_initial'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('prompt_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('system_prompt', sa.Text(), nullable=False),
    sa.Column('user_prompt', sa.Text(), nullable=False),
    sa.Column('ai_response', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_prompt_logs_id'), 'prompt_logs', ['id'], unique=False)
    op.create_index(op.f('ix_prompt_logs_user_id'), 'prompt_logs', ['user_id'], unique=False)
    # op.add_column('users', sa.Column('gender', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_column('users', 'gender')
    op.drop_index(op.f('ix_prompt_logs_user_id'), table_name='prompt_logs')
    op.drop_index(op.f('ix_prompt_logs_id'), table_name='prompt_logs')
    op.drop_table('prompt_logs')
    # ### end Alembic commands ###
