"""add_equipment_and_user_profile

Revision ID: 6f4ed9bbcc03
Revises: f7a50c10c5eb
Create Date: 2026-06-25 12:21:14.581981

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6f4ed9bbcc03'
down_revision: Union[str, Sequence[str], None] = 'f7a50c10c5eb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('equipment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_equipment_id'), 'equipment', ['id'], unique=False)
    op.create_index(op.f('ix_equipment_name'), 'equipment', ['name'], unique=True)
    op.create_table('excersice_equipment',
    sa.Column('excersice_id', sa.Integer(), nullable=False),
    sa.Column('equipment_id', sa.Integer(), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['equipment_id'], ['equipment.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['excersice_id'], ['excersices.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('excersice_id', 'equipment_id')
    )
    op.create_table('programming_matrix',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('goal_code', sa.String(length=50), nullable=False),
    sa.Column('level_code', sa.String(length=50), nullable=False),
    sa.Column('volume', sa.String(length=50), nullable=False),
    sa.Column('sets', sa.Integer(), nullable=False),
    sa.Column('reps', sa.String(length=50), nullable=False),
    sa.Column('rest', sa.String(length=50), nullable=False),
    sa.Column('method_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['method_id'], ['methods.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_programming_matrix_id'), 'programming_matrix', ['id'], unique=False)
    op.create_table('user_disease',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('disease_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['disease_id'], ['conditions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'disease_id')
    )
    op.create_table('user_equipment',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('equipment_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['equipment_id'], ['equipment.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'equipment_id')
    )
    op.create_table('user_pathology',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('pathology_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['pathology_id'], ['conditions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'pathology_id')
    )
    op.create_table('user_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('goal_id', sa.Integer(), nullable=True),
    sa.Column('level_id', sa.Integer(), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('weight', sa.Float(), nullable=True),
    sa.Column('height', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['goal_id'], ['goals.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['level_id'], ['levels.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_column('excersices', 'secondary_tool')
    op.drop_column('excersices', 'primary_tool')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('excersices', sa.Column('primary_tool', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.add_column('excersices', sa.Column('secondary_tool', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.drop_table('user_profiles')
    op.drop_table('user_pathology')
    op.drop_table('user_equipment')
    op.drop_table('user_disease')
    op.drop_index(op.f('ix_programming_matrix_id'), table_name='programming_matrix')
    op.drop_table('programming_matrix')
    op.drop_table('excersice_equipment')
    op.drop_index(op.f('ix_equipment_name'), table_name='equipment')
    op.drop_index(op.f('ix_equipment_id'), table_name='equipment')
    op.drop_table('equipment')
    # ### end Alembic commands ###
