"""add_tier_to_user_and_week_to_user_routine

Revision ID: c912d5a06ceb
Revises: 5b6fad118fb2
Create Date: 2026-08-22 23:14:19.953552

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c912d5a06ceb'
down_revision: Union[str, Sequence[str], None] = '5b6fad118fb2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_routines', sa.Column('week', sa.Integer(), server_default='1', nullable=False))
    op.add_column('users', sa.Column('tier', sa.Enum('BASIC', 'PREMIUM', name='usertier'), server_default='BASIC', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'tier')
    op.drop_column('user_routines', 'week')
    # ### end Alembic commands ###
