"""Add session_durations and workout_places tables

Revision ID: 8f8ffbb9fdd2
Revises: 89f6bc157c13
Create Date: 2026-08-05 19:13:05.070802

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8f8ffbb9fdd2'
down_revision: Union[str, Sequence[str], None] = '89f6bc157c13'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('session_durations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_session_durations_code'), 'session_durations', ['code'], unique=True)
    op.create_index(op.f('ix_session_durations_id'), 'session_durations', ['id'], unique=False)
    op.create_index(op.f('ix_session_durations_name'), 'session_durations', ['name'], unique=True)
    op.create_table('workout_places',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workout_places_code'), 'workout_places', ['code'], unique=True)
    op.create_index(op.f('ix_workout_places_id'), 'workout_places', ['id'], unique=False)
    op.drop_index(op.f('idx_excersice_condition_ex_cond'), table_name='excersice_condition')
    op.drop_index(op.f('idx_excersice_equipment_ex_eq'), table_name='excersice_equipment')
    op.drop_index(op.f('idx_excersice_goal_ex_goal'), table_name='excersice_goal')
    op.drop_index(op.f('idx_excersices_name_trgm'), table_name='excersices', postgresql_ops={'name': 'gin_trgm_ops'}, postgresql_using='gin')
    op.drop_index(op.f('idx_programming_matrix_goal_level'), table_name='programming_matrix')
    op.drop_index(op.f('idx_user_disease_user_cond'), table_name='user_disease')
    op.drop_index(op.f('idx_user_equipment_user_eq'), table_name='user_equipment')
    op.drop_index(op.f('idx_user_pathology_user_cond'), table_name='user_pathology')
    op.drop_index(op.f('idx_user_profiles_goal_level'), table_name='user_profiles')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('idx_user_profiles_goal_level'), 'user_profiles', ['goal_id', 'level_id'], unique=False)
    op.create_index(op.f('idx_user_pathology_user_cond'), 'user_pathology', ['user_id', 'pathology_id'], unique=False)
    op.create_index(op.f('idx_user_equipment_user_eq'), 'user_equipment', ['user_id', 'equipment_id'], unique=False)
    op.create_index(op.f('idx_user_disease_user_cond'), 'user_disease', ['user_id', 'disease_id'], unique=False)
    op.create_index(op.f('idx_programming_matrix_goal_level'), 'programming_matrix', ['goal_code', 'level_code'], unique=False)
    op.create_index(op.f('idx_excersices_name_trgm'), 'excersices', ['name'], unique=False, postgresql_ops={'name': 'gin_trgm_ops'}, postgresql_using='gin')
    op.create_index(op.f('idx_excersice_goal_ex_goal'), 'excersice_goal', ['excersice_id', 'goal_id'], unique=False)
    op.create_index(op.f('idx_excersice_equipment_ex_eq'), 'excersice_equipment', ['excersice_id', 'equipment_id'], unique=False)
    op.create_index(op.f('idx_excersice_condition_ex_cond'), 'excersice_condition', ['excersice_id', 'condition_id'], unique=False)
    op.drop_index(op.f('ix_workout_places_id'), table_name='workout_places')
    op.drop_index(op.f('ix_workout_places_code'), table_name='workout_places')
    op.drop_table('workout_places')
    op.drop_index(op.f('ix_session_durations_name'), table_name='session_durations')
    op.drop_index(op.f('ix_session_durations_id'), table_name='session_durations')
    op.drop_index(op.f('ix_session_durations_code'), table_name='session_durations')
    op.drop_table('session_durations')
    # ### end Alembic commands ###
