"""create_leisure_activities_tables

Revision ID: 14ec06419b87
Revises: 0389fc0104a7
Create Date: 2026-08-16 09:51:27.289481

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '14ec06419b87'
down_revision: Union[str, Sequence[str], None] = '0389fc0104a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('leisure_activities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_leisure_activities_code'), 'leisure_activities', ['code'], unique=True)
    op.create_index(op.f('ix_leisure_activities_id'), 'leisure_activities', ['id'], unique=False)
    op.create_index(op.f('ix_leisure_activities_name'), 'leisure_activities', ['name'], unique=True)
    op.create_table('user_leisure_activity',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('leisure_activity_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['leisure_activity_id'], ['leisure_activities.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'leisure_activity_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_leisure_activity')
    op.drop_index(op.f('ix_leisure_activities_name'), table_name='leisure_activities')
    op.drop_index(op.f('ix_leisure_activities_id'), table_name='leisure_activities')
    op.drop_index(op.f('ix_leisure_activities_code'), table_name='leisure_activities')
    op.drop_table('leisure_activities')
    # ### end Alembic commands ###
